apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: noobaa-endpoint
rules:
- apiGroups:
  - noobaa.io
  resources:
  - '*'
  - noobaas
  - backingstores
  - bucketclasses
  - noobaas/finalizers
  - backingstores/finalizers
  - bucketclasses/finalizers
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io 
  resourceNames:
  - noobaa-endpoint 
  resources:
  - securitycontextconstraints 
  verbs: 
  - use
