apiVersion: v1
kind: ServiceAccount
metadata:
  name: noobaa
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.noobaa-mgmt: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"noobaa-mgmt"}}'
