apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: noobaa
  name: s3
spec:
  port:
    targetPort: s3-https
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: reencrypt
  to:
    kind: Service
    name: s3
    weight: 100
  wildcardPolicy: None
