apiVersion: v1
kind: Service
metadata:
  name: sts
  labels:
    app: noobaa
spec:
  type: LoadBalancer
  selector:
    noobaa-s3: SYSNAME
  ports:
    - port: 443
      targetPort: 7443
      name: sts-https

