apiVersion: v1
kind: Service
metadata:
  name: noobaa-db
  labels:
    app: noobaa
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: 'noobaa-db-serving-cert'
    service.alpha.openshift.io/serving-cert-secret-name: 'noobaa-db-serving-cert'
spec:
  type: ClusterIP
  selector:
    noobaa-db: SYSNAME
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
